@finance.manager.api_HostAddress = http://localhost:5046

GET {{finance.manager.api_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{finance.manager.api_HostAddress}}/hello
Accept: application/json

###
GET {{finance.manager.api_HostAddress}}/plaid-api-status
Accept: application/json

